<?php

namespace App\Services;

use App\Models\AppSetting;
use App\Models\InventoryItem;
use Illuminate\Support\Facades\Mail;

class NotificationService
{
    /**
     * Checks low stock and expiring items, and optionally sends notification email.
     */
    public static function checkAlerts(): array
    {
        $lowStockItems = InventoryItem::whereColumn('current_stock', '<=', 'min_stock_threshold')
            ->with('category')
            ->get();

        $expiringItems = InventoryItem::whereNotNull('expiry_date')
            ->whereDate('expiry_date', '<=', now()->addDays(7))
            ->with('category')
            ->get();

        return [
            'low_stock' => $lowStockItems,
            'expiring' => $expiringItems,
        ];
    }

    /**
     * Sends daily summary report email synchronously.
     */
    public static function sendDailySummaryEmail(array $summaryData): bool
    {
        $adminEmail = AppSetting::getByKey('notification_email', config('mail.from.address'));

        if (!$adminEmail) {
            return false;
        }

        try {
            // Send log email or standard mail
            Mail::raw("Daily Closing Summary Report for " . date('Y-m-d') . "\n\n" .
                "Total Sales Revenue: $" . number_format($summaryData['total_sales'] ?? 0, 2) . "\n" .
                "Total Purchases Cost: $" . number_format($summaryData['total_purchases'] ?? 0, 2) . "\n" .
                "Total Expenses: $" . number_format($summaryData['total_expenses'] ?? 0, 2) . "\n" .
                "Net Profit Today: $" . number_format($summaryData['net_profit'] ?? 0, 2) . "\n\n" .
                "Low Stock Items Alert Count: " . count($summaryData['low_stock'] ?? []) . "\n" .
                "Generated by Restaurant Inventory System.", function ($message) use ($adminEmail) {
                $message->to($adminEmail)
                    ->subject("Daily Restaurant Closing Summary - " . date('Y-m-d'));
            });

            AuditLogService::log("Sent Daily Closing Summary Email to " . $adminEmail, "settings");
            return true;
        } catch (\Throwable $e) {
            return false;
        }
    }
}
