<?php

namespace App\Services;

use App\Models\AppSetting;
use App\Models\PurchaseItem;
use Illuminate\Support\Facades\Mail;

class NotificationService
{
    /**
     * Checks items reaching or exceeding the configured used amount threshold percentage.
     */
    public static function checkAlerts(): array
    {
        $thresholdPercent = (float) AppSetting::getByKey('expiry_warning_threshold', '80');
        $thresholdRatio = $thresholdPercent / 100;

        $expiryWarnings = PurchaseItem::with('purchase.supplier')
            ->where('quantity', '>', 0)
            ->whereRaw('(used_amount / quantity) >= ?', [$thresholdRatio])
            ->orderByDesc('id')
            ->get();

        return [
            'expiring' => $expiryWarnings,
            'threshold_percentage' => $thresholdPercent,
        ];
    }

    /**
     * Get all active system notifications (expiry warnings, threshold usage, etc.)
     */
    public static function getAllNotifications(): array
    {
        $alerts = self::checkAlerts();
        $notifications = [];

        foreach ($alerts['expiring'] as $item) {
            $usedPercent = $item->quantity > 0 ? round(($item->used_amount / $item->quantity) * 100, 1) : 0;
            $notifications[] = [
                'id' => $item->id,
                'title' => "High Ingredient Usage ({$usedPercent}%)",
                'message' => "Ingredient '{$item->ingredient_name}' has reached {$usedPercent}% usage.",
                'type' => 'warning',
                'created_at' => $item->created_at?->toIso8601String() ?? now()->toIso8601String(),
            ];
        }

        return $notifications;
    }

    /**
     * Sends daily summary report email synchronously.
     */
    public static function sendDailySummaryEmail(array $summaryData): bool
    {
        $adminEmail = AppSetting::getByKey('notification_email', config('mail.from.address'));

        if (!$adminEmail) {
            return false;
        }

        try {
            Mail::raw("Daily Closing Summary Report for " . date('Y-m-d') . "\n\n" .
                "Total Sales Revenue: $" . number_format($summaryData['total_sales'] ?? 0, 2) . "\n" .
                "Total Purchases Cost: $" . number_format($summaryData['total_purchases'] ?? 0, 2) . "\n" .
                "Total Expenses: $" . number_format($summaryData['total_expenses'] ?? 0, 2) . "\n" .
                "Net Profit Today: $" . number_format($summaryData['net_profit'] ?? 0, 2) . "\n\n" .
                "Expiry / Usage Warnings Count: " . count($summaryData['expiring'] ?? []) . "\n" .
                "Generated by Restaurant Management System.", function ($message) use ($adminEmail) {
                $message->to($adminEmail)
                    ->subject("Daily Restaurant Closing Summary - " . date('Y-m-d'));
            });

            AuditLogService::log("Sent Daily Closing Summary Email to " . $adminEmail, "settings");
            return true;
        } catch (\Throwable $e) {
            return false;
        }
    }
}
